config/routes.rb
Chesschool::Application.routes.draw do

  match '/rate' => 'rater#create', :as => 'rate'

  mount Ckeditor::Engine => '/ckeditor'

  resources :invitations

  root to: 'welcome#index'

  match '/logout' => 'welcome#logout', :as => :logout
  match '/portal_authorize' => redirect('http://localhost:3001/api/get_user?source=chess'), as: :portal_auth
  match '/signup/:invitation_token', controller: :users, action: :new, via: :get, as: :sign_up

  resources :password_restore

  resources :welcome do
    collection do
      get :about
      post :do_login
      get :forgot
      get 'activate/(:token)' => 'welcome#activate', as: :activate
    end
  end

  resources :users

  resources :messages

  resources :games do
    member do
      get 'make_move/(:id)' => 'games#make_move', as: :make_move
    end
  end

  resources :teams, :shallow => true do
    member do
      post :rate
      get :join
    end

  end

  resources :news do
    collection do
      post 'rate/(:id)' => 'news#rate', as: :rate
    end
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  include Extensions::LoginExt
  include Extensions::PortalIntegration

  before_filter :authorize_access, :except => [:logout, :index, :do_login]

  def authorize_access
    unless logged_in?
      redirect_to_with_notice root_path, t('notices.login.authorization_required'), :error
    end
  end

  def index
    @invitation = Invitation.new
    redirect_if_logged_in
    @user = User.new
  end

  def logout
    reset_user_session
    reset_session

    redirect_to root_path
  end

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/_login.html.haml
.login-form
  = form_tag(do_login_welcome_index_url) do

    = text_field_tag :email, nil, :placeholder => 'Email'
    = password_field_tag :password, nil, :placeholder => 'Password'

    = submit_tag t('welcome.login.sign_in'), class: 'btn btn-primary login-button', style: 'width:320px'

    .remember-me
      = check_box_tag :remember_me, params[:remember_me], :checked => true
      %div.small-text
        = t('welcome.login.remember_me')

    = link_to t('welcome.login.forgot'), '#restorePasswdModal', 'data-toggle'=>'modal', class: 'forgot_password pull-right'

.register
  = link_to t('welcome.login.register'), new_user_path, :class => 'btn btn-large btn-block btn-success'

= render partial: 'password_restore/new_modal'

app/views/welcome/index.html.haml
.heading
  = t('welcome.title')
.subheading
  = t('welcome.description')
  #javascript-errors
- cache do
  = image_tag 'chess-banner.jpg', style: 'width: 770px'

  = render 'login' unless current_user