config/routes.rb
Chesschool::Application.routes.draw do

  match '/rate' => 'rater#create', :as => 'rate'

  mount Ckeditor::Engine => '/ckeditor'

  resources :invitations

  root to: 'welcome#index'

  match '/logout' => 'welcome#logout', :as => :logout
  match '/portal_authorize' => redirect('http://localhost:3001/api/get_user?source=chess'), as: :portal_auth
  match '/signup/:invitation_token', controller: :users, action: :new, via: :get, as: :sign_up

  resources :password_restore

  resources :welcome do
    collection do
      get :about
      post :do_login
      get :forgot
      get 'activate/(:token)' => 'welcome#activate', as: :activate
    end
  end

  resources :users

  resources :messages

  resources :games do
    member do
      get 'make_move/(:id)' => 'games#make_move', as: :make_move
    end
  end

  resources :teams, :shallow => true do
    member do
      post :rate
      get :join
    end

  end

  resources :news do
    collection do
      post 'rate/(:id)' => 'news#rate', as: :rate
    end
  end

end

app/models/news.rb
class News < ActiveRecord::Base
  attr_accessible :title, :content, :author_id, :attachments
  ajaxful_rateable :stars => 5, :dimensions => [:likes ], :allow_update => true

  belongs_to :user, foreign_key: :author_id
  belongs_to :team, foreign_key: :author_id

  scope :recent, where('created_at > ?', Time.now - 2.days)
  scope :interesting, where('likes > ?', 3)

  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }

  validates_presence_of :title

  def author
    self.user
  end

  def save_one!(attr)
    self.author_id = attr[:author_id]
    self.title = attr[:title]
    self.content = attr[:content]
    self.likes = attr[:likes] if attr[:likes]
    self.n_type = attr[:n_type] if attr[:n_type]
    self.save!
  end

  def like!(stars, post, dimension)
    self.likes += 1 if stars >= 3
    self.save!
    self.rate(stars, post, dimension)
  end

end

app/controllers/news_controller.rb
class NewsController < WelcomeController
  rescue_from ActiveRecord::RecordInvalid, with: :record_not_valid
  
  before_filter :authorize_access
  caches_action :index
  # GET /news
  # GET /news.json
  def index
    @post = News.new
    @show_post = News.all.first
    @all = News.order('id desc')
    @recent = News.recent.order('id desc')
    @interesting = News.interesting.order('id desc')

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @all_news }
      format.js
    end
  end

  # POST /news
  # POST /news.json
  def create
    @post = News.new()
    
    respond_to do |format|
      if @post.save_one!(params[:news])
        expire_action action: :index
        format.html { redirect_to_with_notice news_index_path, t('notices.news.created') }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: :index }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def update

  end

  # DELETE /news/1
  # DELETE /news/1.json
  def destroy
    @news = News.find(params[:id])
    @news.destroy
    expire_action action: :index

    respond_to do |format|
      format.html { redirect_to news_index_url }
      format.json { head :no_content }
    end
  end

  # POST /rate_news
  # POST /rate_news.json
  def rate
    @post = News.find(params[:id])
    @post.like!(params[:stars], @post, params[:dimension])

    render :update do |page|
      page.replace_html @post.wrapper_dom_id(params), ratings_for(@post, params.merge(:wrap => false))
      page.visual_effect :highlight, @post.wrapper_dom_id(params)
    end
  end
  
  private
  
  def record_not_valid
    respond_to do |format|
      format.html {redirect_to_with_notice news_index_path, t('notices.news.not_valid_error'), :error }
    end
  end  
end

app/helpers/news_helper.rb
module NewsHelper

  def attachment_tag(post, options = {})
    size = options[:small] ? '70x70' : '200x200'
    size = '500x500' if options[:huge]
    clazz = options[:rounded] ? 'img-circle' : 'img-polaroid'

    image_tag("files/news/#{post.attachments}", size: size, class: clazz)

  end

end

app/views/news/_all.html.haml
%br
%div(class='tab-content news')
  - @all.each do |post|
    - cache(post) do
      #post
        .left_box
          = avatar_tag post.author, small: true
        .right_box
          .title
            = link_to  post.title, '#showPostModal', 'data-toggle' => :modal
          - if current_user.can_create_news?
            %div(style='float:right;position:relative')
              = link_to t('globals.destroy'), news_path(post), method: :delete, confirm: 'Are you sure?', class: 'btn btn-small btn-danger'
          .content
            = truncate(post.content, length: 300).html_safe
            |
            = link_to 'Read more', '#showPostModal', 'data-toggle' => :modal
          .post-footer
            .likes
              = ratings_for post, dimension: :likes, remote_options: {url: rate_news_index_path(post)}
            .created
              = post.created_at.strftime('%d %B %Y')

app/views/news/_form_modal.html.haml
%div{class:'modal hide fade', id:'createNew', tabindex:'-1', role:'dialog', 'aria-hidden'=>'true', style: 'height: 700px;width:900px;'}
  .modal-header
    %button{type:'button', class:'close', 'data-dismiss'=>'modal', 'aria-hidden'=>'true'}
      ×
    .modal-hd
      = t('news.modals.create')
    .modal-desc
      = t('news.modals.create_desc')
  .modal-body(style='max-height: 800px !important; height:800px')
    = simple_form_for @post, validate: true do |f|
      = f.input :author_id, as: :hidden, input_html: { value: current_user.id }
      = f.input :title
      = f.input :content, label: false, :as => :ckeditor, input_html: {:ckeditor => {width: '800px', :toolbar => "Easy"}}
      = f.submit nil, :class => 'btn btn-primary'
      <button class="btn" data-dismiss="modal" aria-hidden="true">
      %i.icon-remove
      = t('globals.close')
      </button>

app/views/news/_interesting.html.haml
%br
%div(class='tab-content news')
  - @interesting.each do |post|
    - cache(post) do
      #post
        .left_box
          = avatar_tag post.author, small: true
        .right_box
          .title
            = link_to  post.title, '#showPostModal', 'data-toggle' => :modal
          - if current_user.can_create_news?
            %div(style='float:right;position:relative')
              = link_to t('globals.destroy'), news_path(post), method: :delete, confirm: 'Are you sure?', class: 'btn btn-danger'
          .content
            = truncate(post.content, length: 300).html_safe
            |
            = link_to 'Read more', '#showPostModal', 'data-toggle' => :modal
          .post-footer
            .likes
              = ratings_for post, :remote_options => {:url => rate_news_index_path(post)}
            .created
              = post.created_at.strftime('%d %B %Y')

app/views/news/_recent.html.haml
%br
%div(class='tab-content news')
  - @recent.each do |post|
    - cache(post) do
      #post
        .left_box
          = avatar_tag post.author, small: true
        .right_box
          .title
            = link_to  post.title, '#showPostModal', 'data-toggle' => :modal
          - if current_user.can_create_news?
            %div(style='float:right;position:relative')
              = link_to t('globals.destroy'), news_path(post), method: :delete, confirm: 'Are you sure?', class: 'btn btn-danger'
          .content
            = truncate(post.content, length: 300).html_safe
            |
            = link_to 'Read more', '#showPostModal', 'data-toggle' => :modal
          .post-footer
            .likes
              = ratings_for post, remote_options: {url: rate_news_index_path(post)}
            .created
              = post.created_at.strftime('%d %B %Y')

app/views/news/_show_modal.html.haml
%div{class:'modal hide fade', id:'showPostModal', tabindex:'-1', role:'dialog', 'aria-hidden'=>'true', style: 'min-height: 300px'}
  .modal-header
    %button{type:'button', class:'close', 'data-dismiss'=>'modal', 'aria-hidden'=>'true'}
      ×
    .modal-hd
      = t('news.modals.show')
    .modal-desc
      = t('news.modals.show_desc')
  .modal-body(style='min-width:500px;max-height:550px;overflow:scroll;')
    = @show_post.title
    .content
      = @show_post.content
    = attachment_tag(@show_post, huge: true)
    <button class="btn" data-dismiss="modal" aria-hidden="true">
    %i.icon-remove
    = t('globals.close')
    </button>

app/views/news/index.html.haml
%div(class='tabbable')
  %ul{:class=>'nav nav-tabs'}
    %li{class:  "#{'active' if params[:tab] == 'all'}"}
      = link_to t('news.all.header'), news_index_path(tab: :all), remote: true,  'data-toggle'=>'tab'
    %li{class: "#{'active' if params[:tab] == 'recent'}"}
      = link_to t('news.recent.header'), news_index_path(tab: :recent), remote: true, 'data-toggle'=>'tab'
    %li{class:  "#{'active' if params[:tab] == 'interesting'}"}
      = link_to t('news.interesting.header'), news_index_path(tab: :interesting), remote: true, 'data-toggle'=>'tab'


- if current_user.can_create_news?
  = link_to 'Create Some News', '#createNew', 'data-toggle'=> 'modal', class: 'btn btn-primary'
  = render 'form_modal'

#news-list
  = render partial: 'news/all'

app/views/news/index.js.erb
$("#news-list").hide();
$("#news-list").html("<%= escape_javascript render partial: "#{params[:tab]}" %>");
$("#news-list").slideDown('slow');