config/routes.rb
Chesschool::Application.routes.draw do

  match '/rate' => 'rater#create', :as => 'rate'

  mount Ckeditor::Engine => '/ckeditor'

  resources :invitations

  root to: 'welcome#index'

  match '/logout' => 'welcome#logout', :as => :logout
  match '/portal_authorize' => redirect('http://localhost:3001/api/get_user?source=chess'), as: :portal_auth
  match '/signup/:invitation_token', controller: :users, action: :new, via: :get, as: :sign_up

  resources :password_restore

  resources :welcome do
    collection do
      get :about
      post :do_login
      get :forgot
      get 'activate/(:token)' => 'welcome#activate', as: :activate
    end
  end

  resources :users

  resources :messages

  resources :games do
    member do
      get 'make_move/(:id)' => 'games#make_move', as: :make_move
    end
  end

  resources :teams, :shallow => true do
    member do
      post :rate
      get :join
    end

  end

  resources :news do
    collection do
      post 'rate/(:id)' => 'news#rate', as: :rate
    end
  end

end

app/controllers/password_restore_controller.rb
class PasswordRestoreController < ApplicationController

  def new
  end

  def create
    user = User.find_by_email(params[:restore][:email])
    user.send_password_reset if user
    redirect_to_with_notice root_url, t('welcome.registration.password_restore.email_sent_reset')
  end

  def edit
    @user = User.find_by_password_reset_token!(params[:id])
  end

  def update
    @user = User.find_by_password_reset_token!(params[:id])
    unless @user.from_facebook?
      if params[:user][:confirm_password] == params[:user][:password]
        params[:user].delete :confirm_password
        if @user.password_reset_sent_at < 2.hours.ago
          redirect_to_with_notice root_path, t('welcome.registration.password_restore.pass_expired'), :error
        elsif @user.reset_password!(params[:user])
          redirect_to_with_notice root_url, t('welcome.registration.password_restore.pass_reset'), :success
        else
          render :edit
        end
      else
        redirect_to_with_notice root_path, t('welcome.registration.password_restore.confirmation_not_match'), :error
      end
    end
  end

end

app/views/password_restore/_new_modal.html.haml
%div{class:'modal hide fade', id:'restorePasswdModal', tabindex:'-1', role:'dialog', 'aria-hidden'=>'true'}
  .modal-header
    %button{type:'button', class:'close', 'data-dismiss'=>'modal', 'aria-hidden'=>'true'}
      ×
    .modal-hd
      = t('welcome.registration.restore_passwd')
    .modal-desc
      = t('welcome.registration.restore_hint')
  .modal-body
    .provide-email
      = simple_form_for :restore, { url: password_restore_index_path, method: :post } do |f|
        = f.input :email
        .modal-footer
          = f.button :submit, t('welcome.registration.restore_passwd'), class: 'btn btn-success'
          %button.btn.btn-small(data-dismiss="modal" aria-hidden="true")
            %i.icon-remove
            = t('globals.close')

app/views/password_restore/edit.html.haml
.page-header
  %h1= t('welcome.registration.password_restore.subject')

= simple_form_for @user, url: password_restore_path(params[:id]) do |f|
  .password-reset
    = f.input :password
    = f.input :confirm_password

    = f.button :submit, t('welcome.registration.password_restore.update_password'), class: 'btn btn-success'