config/routes.rb
Chesschool::Application.routes.draw do

  match '/rate' => 'rater#create', :as => 'rate'

  mount Ckeditor::Engine => '/ckeditor'

  resources :invitations

  root to: 'welcome#index'

  match '/logout' => 'welcome#logout', :as => :logout
  match '/portal_authorize' => redirect('http://localhost:3001/api/get_user?source=chess'), as: :portal_auth
  match '/signup/:invitation_token', controller: :users, action: :new, via: :get, as: :sign_up

  resources :password_restore

  resources :welcome do
    collection do
      get :about
      post :do_login
      get :forgot
      get 'activate/(:token)' => 'welcome#activate', as: :activate
    end
  end

  resources :users

  resources :messages

  resources :games do
    member do
      get 'make_move/(:id)' => 'games#make_move', as: :make_move
    end
  end

  resources :teams, :shallow => true do
    member do
      post :rate
      get :join
    end

  end

  resources :news do
    collection do
      post 'rate/(:id)' => 'news#rate', as: :rate
    end
  end

end

app/views/navigation/_flash.html.haml
#flash
  - if flash[:notice]
    %div{:class => 'alert alert-info animated swing', id: 'flash-info'}
      = flash[:notice]
  - if flash[:error]
    %div{:class => 'alert alert-error animated shake', id: 'flash-error'}
      = flash[:error]
  - if flash[:success]
    %div{:class => 'alert alert-success animated tada', id: 'flash-success'}
      = flash[:success]
%div.field_with_errors

app/views/navigation/_footer.html.haml
&copy
= copyright_notice_year_range(2013)
= link_to 'VoolCan Inc.', 'http://dygabox.herokuapp.com/'
All Rights Reserved
.contact
  = t 'welcome.footer.contact'
  = mail_to 'otan256@gmail.com'
.online
  = t('welcome.footer.online', count: online_count)
.timenow
  = Time.now.strftime('%d %B %Y %H:%M')

app/views/navigation/_forum_dropdown.html.haml
%ul.nav
  %li.dropdown
    %a{:class=>"dropdown-toggle", :id=>"dLabel", :role=>"button", 'data-toggle'=>"dropdown", 'data-target'=>"#", :href=>"/"}
      %i.icon-comment
      = t('navigation.header.forum')
      %b.caret
    %ul.dropdown-menu
      %li(class='dropdown-with-icon')
        = image_tag 'icons/all_topics.png', size: '25x25', class: 'dropdown-image'
        = link_to portal_dashboard_link({tab: :news, what: :all}), target: '_blank', class: 'dropdown-li' do
          = t('forum.globals.all_topics')
          %p= t('forum.globals.all_topics_desc')

      %li(class='dropdown-with-icon')
        = image_tag 'icons/unanswered.png', size: '25x25', class: 'dropdown-image'
        = link_to portal_dashboard_link({tab: :news, what: :unanswered}), target: '_blank', class: 'dropdown-li' do
          = t('forum.globals.unanswered_topics')
          %p= t('forum.globals.unanswered_topics_desc')

      %li(class='dropdown-with-icon')
        = image_tag 'icons/my_topics.jpg', size: '25x25', class: 'dropdown-image'
        = link_to portal_dashboard_link({tab: :news, what: :my}), target: '_blank', class: 'dropdown-li' do
          = t('forum.globals.my_topics')
          %p= t('forum.globals.my_topics_desc')

      %li(class='dropdown-with-icon')
        = image_tag 'icons/new_topics.png', size: '25x25', class: 'dropdown-image'
        = link_to portal_dashboard_link({tab: :news, what: :new}), target: '_blank', class: 'dropdown-li' do
          = t('forum.globals.new_topics')
          %p= t('forum.globals.new_topics_desc')

      %li(class='dropdown-with-icon')
        = image_tag 'icons/hot.png', size: '25x25', class: 'dropdown-image'
        = link_to portal_dashboard_link({tab: :news, what: :hot}), target: '_blank', class: 'dropdown-li' do
          = t('forum.globals.hot_topics')
          %p= t('forum.globals.hot_topics_desc')

app/views/navigation/_games_dropdown.html.haml
%ul.nav
  %li.dropdown
    %a{:class=>"dropdown-toggle", :id=>"dLabel", :role=>"button", 'data-toggle'=>"dropdown", 'data-target'=>"#", :href=>"/"}
      %i.icon-leaf
      = t('navigation.header.play')
      %b.caret
    %ul.dropdown-menu
      %li(class='dropdown-with-icon')
        = image_tag 'icons/with-friends.png', size: '25x25', class: 'dropdown-image'
        = link_to games_path, class: 'dropdown-li' do
          = t('games.globals.chess_with_friends')
          %p= t('games.globals.chess_with_friends_desc')

      %li(class='dropdown-with-icon')
        = image_tag 'icons/tournaments.png', size: '25x25', class: 'dropdown-image'
        = link_to games_path, class: 'dropdown-li' do
          = t('games.globals.chess_tournaments')
          %p= t('games.globals.chess_tournaments_desc')

      %li(class='dropdown-with-icon')
        = image_tag 'icons/live-chess.jpg', size: '25x25', class: 'dropdown-image'
        = link_to games_path, class: 'dropdown-li' do
          = t('games.globals.live_chess')
          %p= t('games.globals.live_chess_desc', count: 4)

app/views/navigation/_profile_dropdown.html.haml
%ul{class:'nav pull-right'}
  %li.dropdown
    %a{:class=>"dropdown-toggle", :id=>"dLabel", :role=>"button", 'data-toggle'=>"dropdown", 'data-target'=>"#", :href=>"/"}
      %i.icon-home
      = current_user.first_name
      %b.caret
    %ul.dropdown-menu
      %li(class='dropdown-with-icon')
        = image_tag 'icons/home.png', size: '25x25', class: 'dropdown-image'
        = link_to user_path(current_user.id), class: 'dropdown-li' do
          = t('users.home.title')
          %p= t('users.home.title_desc')

      %li(class='dropdown-with-icon')
        = image_tag 'icons/messages.png', size: '25x25', class: 'dropdown-image'
        = link_to messages_path(tab: 'inbox'), class: 'dropdown-li' do
          = t('users.home.messages')
          %p= t('users.home.messages_desc')

      %li.divider

      %li(class='dropdown-with-icon')
        = image_tag 'icons/logout.gif', size: '25x25', class: 'dropdown-image'
        = link_to logout_path, class: 'dropdown-li' do
          = t('globals.sign_out')
          %p= t('globals.sign_out_desc')

app/views/navigation/_social_dropdown.html.haml
%ul.nav
  %li.dropdown
    %a{:class=>"dropdown-toggle", :id=>"dLabel", :role=>"button", 'data-toggle'=>"dropdown", 'data-target'=>"#", :href=>"/"}
      %i.icon-share
      = t('navigation.header.social')
      %b.caret
    %ul.dropdown-menu
      %li(class='dropdown-with-icon')
        = image_tag 'icons/members.jpg', size: '25x25', class: 'dropdown-image'
        = link_to users_path, class: 'dropdown-li' do
          = t('social.globals.members')
          %p= t('social.globals.members_desc')

      %li(class='dropdown-with-icon')
        = image_tag 'icons/invite.jpg', size: '25x25', class: 'dropdown-image'
        = link_to '#invitationModal', 'data-toggle'=> 'modal', class: 'dropdown-li' do
          = t('social.globals.invite')
          %p= t('social.globals.invite_desc', limit: current_user.invitation_limit)

      %li(class='dropdown-with-icon')
        = image_tag 'icons/team.jpg', size: '25x25', class: 'dropdown-image'
        = link_to teams_path, class: 'dropdown-li' do
          = t('social.globals.teams')
          %p= t('social.globals.teams_desc')

      %li(class='dropdown-with-icon')
        = image_tag 'icons/news.png', size: '25x25', class: 'dropdown-image'
        = link_to news_index_path(tab: 'all'), class: 'dropdown-li' do
          = t('social.globals.news')
          %p= t('social.globals.news_desc')

      %li(class='dropdown-with-icon')
        = image_tag 'icons/blogs.png', size: '25x25', class: 'dropdown-image'
        - # TODO!!!!
        = link_to '#', class: 'dropdown-li' do
          = t('social.globals.blogs')
          %p= t('social.globals.blogs_desc')

= render 'invitations/invitation_modal'

app/views/navigation/_study_dropdown.html.haml
%ul.nav
  %li.dropdown
    %a{:class=>"dropdown-toggle", :id=>"dLabel", :role=>"button", 'data-toggle'=>"dropdown", 'data-target'=>"#", :href=>"/"}
      %i.icon-book
      = t('navigation.header.study')
      %b.caret
    %ul.dropdown-menu
      %li(class='dropdown-with-icon')
        = image_tag 'icons/lessons.png', size: '25x25', class: 'dropdown-image'
        = link_to games_path, class: 'dropdown-li' do
          = t('study.globals.lessons')
          %p= t('study.globals.lessons_desc')

      %li(class='dropdown-with-icon')
        = image_tag 'icons/article.jpg', size: '25x25', class: 'dropdown-image'
        = link_to news_index_path, class: 'dropdown-li' do
          = t('study.globals.articles')
          %p= t('study.globals.articles_desc')

      %li(class='dropdown-with-icon')
        = image_tag 'icons/convensions.gif', size: '25x25', class: 'dropdown-image'
        = link_to games_path, class: 'dropdown-li' do
          = t('study.globals.convensions')
          %p= t('study.globals.convensions_desc')

      %li(class='dropdown-with-icon')
        = image_tag 'icons/tactics.gif', size: '25x25', class: 'dropdown-image'
        = link_to games_path, class: 'dropdown-li' do
          = t('study.globals.tactics')
          %p= t('study.globals.tactics_desc')

      %li(class='dropdown-with-icon')
        = image_tag 'icons/puzzles.png', size: '25x25', class: 'dropdown-image'
        = link_to games_path, class: 'dropdown-li' do
          = t('study.globals.puzzles')
          %p= t('study.globals.puzzles_desc')

      %li(class='dropdown-with-icon')
        = image_tag 'icons/basics.jpg', size: '25x25', class: 'dropdown-image'
        = link_to games_path, class: 'dropdown-li' do
          = t('study.globals.basics')
          %p= t('study.globals.basics_desc')

app/views/navigation/header.html.haml
- cache do
  %div{class: 'navbar navbar-inverse navbar-fixed-top'}
    %div.navbar-inner
      %div.container
        %a{class:'btn btn-navbar', 'data-toggle'=>'collapse', 'data-target'=>'.nav-collapse'}
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar

        = link_to t('globals.chesschool'), root_path, class: :brand
        %div.nav-collapse
          - if current_user.present?
            = render partial: 'navigation/games_dropdown'
            = render partial: 'navigation/study_dropdown'
            = render partial: 'navigation/social_dropdown'
            = render partial: 'navigation/forum_dropdown'
            = render partial: 'navigation/profile_dropdown'